### ISSUE TITLE
QuodLIbet 4.6.1 unable to make web request

### ISSUE THREAD

**Issue by erixtekila** [jdykstra/quodlibet#7]
Steps to reproduce
------------------
Install Musikbrainz plugin.
Use it on a playlist will produce an error.
It seems that no request could be emitted from the sonoma application…?

### Which operating system 
MacOS 10.14...

Additional Information
----------------------
<img width="654" alt="Capture d’écran 2024-05-04 à 16 00 15" src="https://github.com/jdykstra/quodlibet/assets/605404/8518423d-52b5-47df-922f-9eccd5a10f7b">

**Comment by jdykstra** [comment]
I apologize for the delay in responding to your report.  Apparently I missed the notification email from GitHub.

When I tried to reproduce your problem on MacOS 15.1.1, I discovered that popup menus are not working at all.  I'll investigate your bug after I track #9 down.

Perhaps this bug should be moved to quodlibet/quodlibet, since they've added the QL 4.6.1 MacOS build to their downloads page, but I'm going to leave it here for now.  I'm almost certainly going to be the one working on it, no matter where the bug is tracked.

**Comment by jdykstra** [comment]
E: [0000.000] fake.plugins.brainz.query.__run: musicbrainz.py:525:_safe_read: musicbrainzngs.musicbrainz.NetworkError: caused by: <urlopen error unknown url type: https>

jwd@oak MacOS $ PYTHONHOME=/Applications/QuodLibet.app/Contents/Resources/ python3
Python 3.11.6 (main, Dec 27 2023, 14:54:59) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
print(ssl.OPENSSL_VERSION)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ssl.py", line 100, in <module>
ModuleNotFoundError: No module named '_ssl'
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ssl' is not defined

SSL library wasn't found during the Python build.

**Comment by jdykstra** [comment]
The immediate cause of this is that the Python interpreter we include in the application bundle isn't being built with SSL support.  (MusicBrainz requires https.)  The root cause is a deficiency in the Python build scripts.  The "--with-openssl" configure parameter is ignored when the "_ssl" module is built by the top-level setup.py script.

**Comment by erixtekila** [comment]
Thanks ! 
That works just great
